In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


'c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


'c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.


In [3]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


'c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.


In [4]:
pip install sklearn

Note: you may need to restart the kernel to use updated packages.


'c:\Users\ASUS' is not recognized as an internal or external command,
operable program or batch file.


In [7]:
import os
import pandas as pd
import numpy as np
import tensorflow as tf

In [15]:
os.path.join('train.csv')

'train.csv'

In [18]:
df = pd.read_csv("C:/Users/ASUS ROG/Projects/Toxic-Comments-Identification/train.csv")

In [19]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [20]:
from tensorflow.keras.layers import TextVectorization

In [21]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [22]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [23]:
df[df.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [24]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [25]:
x=df['comment_text']
y=df[df.columns[2:]].values

In [26]:
#Defining the no of words in our vocabulary
max_no_of_words=200000

In [27]:
vectorizer = TextVectorization(max_tokens=max_no_of_words,
                           output_sequence_length=1800,
                           output_mode='int')

In [28]:
#passing the input through vectorizer so it can learn
vectorizer.adapt(x.values)

In [29]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [30]:
#Tokenization of input sentences
vectorized_text=vectorizer(x.values)

In [31]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [32]:
#Creating tensorflow data pipeline
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(1600)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [33]:
#Grabs hold of a batch of input
batch_x, batch_y=dataset.as_numpy_iterator().next()

In [34]:
len(dataset)

9974

In [35]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [36]:
train_generator=train.as_numpy_iterator()

In [37]:
train_generator.next()

(array([[   23,    54,     9, ...,     0,     0,     0],
        [ 1048,   880,   179, ...,     0,     0,     0],
        [ 2522,     5,   265, ...,     0,     0,     0],
        ...,
        [12853,   764,   369, ...,     0,     0,     0],
        [    8,    19,   612, ...,     0,     0,     0],
        [  708,    17,     2, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1]], dtype=int64))

In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [30]:
model=Sequential()
model.add(Embedding(max_no_of_words+1,32))
model.add(Bidirectional(LSTM(32,activation='tanh')))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(256,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(128,activation='relu'))
model.add(Dense(6,activation='sigmoid'))

In [31]:
model.compile(loss='BinaryCrossentropy',optimizer='Adam')

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dropout_1 (Dropout)         (None, 256)               0         
                                                        

In [34]:
history = model.fit(train, epochs=5, validation_data=val)

Epoch 1/15
 323/6981 [>.............................] - ETA: 1:28:27 - loss: 0.0818

In [35]:
batch = test.as_numpy_iterator().next()

In [36]:
input_text = vectorizer('Your content is garbage')

In [39]:
pred=model.predict(np.expand_dims(input_text,0))

1/1 [==============================] - 0s 87ms/step


In [40]:
(pred > 0.5).astype(int)

array([[1, 0, 0, 0, 0, 0]])

In [41]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [42]:
(model.predict(batch_X) > 0.5).astype(int)

1/1 [==============================] - 0s 117ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0]])

In [44]:
pred.shape

(1, 6)

In [45]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [46]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
#Looping through every single batch
for batch in test.as_numpy_iterator(): 
    #Unpacking our batch
    X_true, y_true = batch
    #Making a prediction
    yhat = model.predict(X_true)
    
    #Flatten our predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    #Updating the metrics
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

In [48]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.7415027022361755, Recall:0.699578046798706, Accuracy:0.476429283618927


In [51]:
model.save('toxicity.h5')

In [39]:
model = tf.keras.models.load_model('toxicity.h5',compile=False)

In [29]:
input_str = vectorizer('i will destroy your peace and mind!')

In [30]:
pred = model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 0s 486ms/step


In [8]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [32]:
pred

array([[0.7073386 , 0.02030649, 0.05140555, 0.18038924, 0.15360351,
        0.29525974]], dtype=float32)

In [1]:
!pip install grade jinja2

In [4]:
!pip install gradio

     -------------------------------------- 17.3/17.3 MB 172.1 kB/s eta 0:00:00
  Using cached aiofiles-23.1.0-py3-none-any.whl (14 kB)
  Using cached aiohttp-3.8.4-cp38-cp38-win_amd64.whl (324 kB)
  Using cached fastapi-0.95.1-py3-none-any.whl (56 kB)
  Using cached ffmpy-0.3.0-py3-none-any.whl
     ------------------------------------ 287.9/287.9 kB 175.8 kB/s eta 0:00:00
  Using cached httpx-0.24.0-py3-none-any.whl (75 kB)
     ------------------------------------ 224.5/224.5 kB 279.7 kB/s eta 0:00:00
  Using cached mdit_py_plugins-0.3.3-py3-none-any.whl (50 kB)
     ------------------------------------ 196.1/196.1 kB 247.8 kB/s eta 0:00:00
  Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
  Using cached python_multipart-0.0.6-py3-none-any.whl (45 kB)
  Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
     -------------------------------------- 58.3/58.3 kB 192.4 kB/s eta 0:00:00
     ------------------------------------ 124.6/124.6 kB 203.5 kB/s eta 0:00:00


In [51]:
import gradio as gr
import gradio.components

In [40]:
input_str = vectorizer('i will destroy your peace and mind!')

In [43]:
res=model.predict(np.expand_dims(input_str,0))

1/1 [==============================] - 1s 802ms/step


In [44]:
res

array([[0.7073386 , 0.02030649, 0.05140555, 0.18038924, 0.15360351,
        0.29525974]], dtype=float32)

In [49]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [52]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

In [53]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7861

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app


1/1 [==============================] - 0s 94ms/step
